# Generated by Django 4.0.1 on 2022-09-30 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doktergigi',
            fields=[
                ('iddoktergigi', models.AutoField(primary_key=True, serialize=False)),
                ('namadoktergigi', models.CharField(max_length=100)),
                ('alamatdoktergigi', models.CharField(max_length=10)),
                ('nohpdoktergigi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pasien',
            fields=[
                ('idpasien', models.AutoField(primary_key=True, serialize=False)),
                ('namapasien', models.CharField(max_length=70)),
                ('jeniskelamin', models.CharField(max_length=15)),
                ('alamatpasien', models.CharField(max_length=15)),
                ('nohppasien', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pelayanan',
            fields=[
                ('idpelayanan', models.AutoField(primary_key=True, serialize=False)),
                ('namapelayanan', models.CharField(max_length=70)),
                ('hargapelayanan', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pendaftaran',
            fields=[
                ('idpendaftaran', models.AutoField(primary_key=True, serialize=False)),
                ('tanggalpendaftaran', models.DateField()),
                ('iddoktergigi', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='app.doktergigi')),
                ('idpasien', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='app.pasien')),
            ],
        ),
        migrations.CreateModel(
            name='detailpelayanan',
            fields=[
                ('iddetailpelayanan', models.AutoField(primary_key=True, serialize=False)),
                ('jumlahpelayanan', models.IntegerField()),
                ('idpelayanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pelayanan')),
                ('idpendaftaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pendaftaran')),
            ],
        ),
    ]
